services:
  terraform:
    image: hashicorp/terraform:1.6.2
    container_name: terraform
    working_dir: /tf
    volumes:
      - ./setup:/tf/setup
      - ./deploy:/tf/deploy
    command: tail -f /dev/null
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - AWS_DEFAULT_REGION=us-east-2
      - TF_WORKSPACE=${TF_WORKSPACE}
